# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'other.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ohter(object):
    def setupUi(self, ohter):
        ohter.setObjectName("ohter")
        ohter.setWindowModality(QtCore.Qt.ApplicationModal)
        ohter.resize(265, 99)
        ohter.setWindowTitle("其他设置")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/plugin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ohter.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(ohter)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.import_css = QtWidgets.QCheckBox(ohter)
        self.import_css.setObjectName("import_css")
        self.horizontalLayout.addWidget(self.import_css)
        self.link_css = LinkCss(ohter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.link_css.sizePolicy().hasHeightForWidth())
        self.link_css.setSizePolicy(sizePolicy)
        self.link_css.setMinimumSize(QtCore.QSize(146, 40))
        self.link_css.setObjectName("link_css")
        self.horizontalLayout.addWidget(self.link_css)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_img_code = QtWidgets.QCheckBox(ohter)
        self.add_img_code.setObjectName("add_img_code")
        self.horizontalLayout_2.addWidget(self.add_img_code)
        self.mod_code = QtWidgets.QPushButton(ohter)
        self.mod_code.setMinimumSize(QtCore.QSize(146, 0))
        self.mod_code.setObjectName("mod_code")
        self.horizontalLayout_2.addWidget(self.mod_code)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ohter)
        self.mod_code.clicked.connect(ohter.open_img_code) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ohter)

    def retranslateUi(self, ohter):
        _translate = QtCore.QCoreApplication.translate
        self.import_css.setText(_translate("ohter", "链接到样式表"))
        self.add_img_code.setText(_translate("ohter", "导入首图代码"))
        self.mod_code.setText(_translate("ohter", "修改代码"))
from myQtClass import LinkCss
import res_rc
